Repository SoftyChoo/nbCamp_week4_assignment, pull requests merged in 2023-08, with the labels that each got.

#14 [Feat] : cardView & Editprofile btn
  .gitignore
  .gradle/8.0/executionHistory/executionHistory.bin
  .gradle/8.0/executionHistory/executionHistory.lock
  .gradle/8.0/fileHashes/fileHashes.bin
  .gradle/8.0/fileHashes/fileHashes.lock
  .gradle/8.0/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/nbcamp_week4_assignment/Adaptor/PostAdaptor.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/MainActivity.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/Object/PostObject.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/ProfileActivity.kt
  app/src/main/res/drawable/post_hj1.jpeg
  app/src/main/res/drawable/post_hj2.jpeg
  app/src/main/res/drawable/post_jh1.jpg
  app/src/main/res/drawable/post_jh2.jpg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/card_item.xml
  app/src/main/res/layout/post_item.xml
Labels: enhancement

#15 [Feat] : Click시 개인 포스트 기능 구현 완료
  app/src/main/java/com/example/nbcamp_week4_assignment/Adaptor/ProfileAdaptor.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/Object/PostObject.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/ProfileActivity.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/SignInActivity.kt
  local.properties
Labels: enhancement

#18 Signin조건문수정 Signup이미지불러오기기능추가
  app/src/main/java/com/example/nbcamp_week4_assignment/Object/UserObject.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/SignInActivity.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/SignUpActivity.kt
  app/src/main/res/layout/activity_sign_up.xml
Labels: documentation

#19 [FEAT] : ID 중복일 경우 회원가입 제한기능 및 회원 가입기능 구현
  app/src/main/java/com/example/nbcamp_week4_assignment/Object/UserObject.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/SignUpActivity.kt
Labels: enhancement

#21 Signup이미지object추가 Userclass이미지추가
  app/src/main/java/com/example/nbcamp_week4_assignment/DataClass/User.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/Object/UserObject.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/SignUpActivity.kt
Labels: documentation

#24 [feat] : 가로 모드
  app/src/main/res/layout-land/activity_edit_profile.xml
  app/src/main/res/layout-land/activity_profile.xml
  app/src/main/res/layout-land/activity_sign_up.xml
  app/src/main/res/layout-land/activity_signin.xml
  app/src/main/res/values-en-rUS/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
Labels: land

#26 [Feat] : strings 언어 적용
  app/src/main/java/com/example/nbcamp_week4_assignment/SignInActivity.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/SignUpActivity.kt
  app/src/main/res/layout-land/activity_edit_profile.xml
  app/src/main/res/layout-land/activity_sign_up.xml
  app/src/main/res/layout-land/activity_signin.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/values-en-rUS/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values/strings.xml
Labels: language

#27 [Feat] : updateData
  app/src/main/java/com/example/nbcamp_week4_assignment/DataClass/Post.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/EditProfileActivity.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/Object/PostObject.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/Object/UserObject.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/ProfileActivity.kt
Labels: enhancement

#28 [FEAT] : EditProfileActivity, ProfileActivity 화면전환 애니메이션 추가
  app/src/main/java/com/example/nbcamp_week4_assignment/EditProfileActivity.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/ProfileActivity.kt
Labels: enhancement

#30 [FEAT] : Adaptor 화면전환 애니메이션 추가
  app/src/main/java/com/example/nbcamp_week4_assignment/Adaptor/ProfileAdaptor.kt
Labels: enhancement

#31 [Feat] : VisibleBtn
  app/src/main/java/com/example/nbcamp_week4_assignment/Adaptor/ProfileAdaptor.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/EditProfileActivity.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/MainActivity.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/Object/UserObject.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/ProfileActivity.kt
  app/src/main/java/com/example/nbcamp_week4_assignment/SignInActivity.kt
  app/src/main/res/layout/profile_item.xml
Labels: enhancement

#33 [Feat] : SignInPage KeyEvent 뒤로가기구현
  app/src/main/java/com/example/nbcamp_week4_assignment/SignInActivity.kt
  app/src/main/res/values-en-rUS/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values/strings.xml
Labels: keycode
